using System.Text;
using AirportManager.API.Common;
using AirportManager.API.DbConnectionFactory.Interfaces;
using AirportManager.API.Helpers;
using AirportManager.API.Repositories.Interfaces;
using Dapper;

namespace AirportManager.API.Repositories.Implementations;

public abstract class GenericRepository<T> : IGenericRepository<T> where T : class
{
    private readonly IDbConnectionFactory _factory;
    private readonly string _tableName = typeof(T).Name.PascalCaseToSnakeCase().Pluralize();

    public GenericRepository(IDbConnectionFactory factory)
    {
        _factory = factory;
        DefaultTypeMap.MatchNamesWithUnderscores = true;
    }

    public async Task<IEnumerable<T>> GetAllAsync(PagingOptions pagingOptions)
    {
        var query = new StringBuilder($"SELECT * FROM {_tableName}");

        if (pagingOptions != null)
        {
            if (pagingOptions.OrderBy != null)
                query.Append($" ORDER BY {pagingOptions.OrderBy.PascalCaseToSnakeCase()}");

            query.Append($" LIMIT {pagingOptions.PageSize} OFFSET {(pagingOptions.Page - 1) * pagingOptions.PageSize}");
        }

        var connection = _factory.CreateConnection();

        return await connection.QueryAsync<T>(query.ToString());
    }

    public async Task<T?> GetByPkAsync(int id)
    {
        var query = $"SELECT * FROM {_tableName} WHERE id = @id LIMIT 1";

        var connection = _factory.CreateConnection();

        return await connection.QueryFirstOrDefaultAsync<T>(query, new { id });
    }

    public async Task<int> CreateAsync(T entity) => await CreateRecordAsync(entity);

    public async Task<int> CreateAsync(T entity, bool isPkAutoGenerated) => await CreateRecordAsync(entity, isPkAutoGenerated);

    public async Task<int> CreateAsync(T entity, bool isPkAutoGenerated, string pkColumnName) => await CreateRecordAsync(entity, isPkAutoGenerated, pkColumnName);

    public async Task<int> UpdateAsync(T entity) => await UpdateRecordAsync(entity);

    public async Task<int> UpdateAsync(T entity, string pkColumnName)
    {
        if (string.IsNullOrWhiteSpace(pkColumnName))
            throw new ArgumentNullException(nameof(pkColumnName));

        return await UpdateRecordAsync(entity, pkColumnName);
    }

    public async Task<int> DeleteAsync(int id) => await DeleteRecordAsync(id);

    public async Task<int> DeleteAsync(int id, string pkColumnName)
    {
        if (string.IsNullOrWhiteSpace(pkColumnName))
            throw new ArgumentNullException(nameof(pkColumnName));

        return await DeleteRecordAsync(id, pkColumnName);
    }

    private async Task<int> CreateRecordAsync(T entity, bool isPkAutoGenerated = true, string pkColumnName = "id")
    {
        if (entity == null)
            throw new ArgumentException("The inserting entity shouldn't be null.");

        var insertQuery = new StringBuilder($"INSERT INTO {_tableName} (");
        var entityProperties = GetProperties();

        var parametersQuery = new StringBuilder();
        var valuesQuery = new StringBuilder();

        foreach (var item in entityProperties)
        {
            var snakeCasedProperty = item.PascalCaseToSnakeCase();
            var matchesPkColumnName = snakeCasedProperty.Equals(pkColumnName.PascalCaseToSnakeCase());

            if (!matchesPkColumnName || (matchesPkColumnName && !isPkAutoGenerated))
            {
                parametersQuery.Append($"{snakeCasedProperty},");
                valuesQuery.Append($"@{item},");
            }
        }

        parametersQuery.Remove(parametersQuery.Length - 1, 1).Append(") VALUES (");
        valuesQuery.Remove(valuesQuery.Length - 1, 1).Append(");");

        insertQuery.Append(parametersQuery).Append(valuesQuery);

        int lastInsertId;
        var connection = _factory.CreateConnection();

        try
        {
            if (isPkAutoGenerated)
            {
                insertQuery.Append("SELECT last_insert_rowid();");
                lastInsertId = await connection.ExecuteScalarAsync<int>(insertQuery.ToString(), entity);
            }
            else
            {
                await connection.ExecuteAsync(insertQuery.ToString(), entity);
                lastInsertId = 0;
            }
        }
        catch
        {
            lastInsertId = -1;
        }

        return lastInsertId;
    }
    private async Task<int> UpdateRecordAsync(T entity, string pkColumnName = "id")
    {
        if (entity == null)
            throw new ArgumentException(nameof(entity));

        var updateQuery = new StringBuilder($"UPDATE {_tableName} SET ");
        var properties = GetProperties();

        var pkProperty = string.Empty;

        pkColumnName = pkColumnName.PascalCaseToSnakeCase();

        foreach (var item in properties)
        {
            var snakeCasedProperty = item.PascalCaseToSnakeCase();

            if (!snakeCasedProperty.Equals(pkColumnName))
                updateQuery.Append($"{snakeCasedProperty}=@{item},");
            else
                pkProperty = item;
        }

        updateQuery.Remove(updateQuery.Length - 1, 1);
        updateQuery.Append($" WHERE {pkColumnName}=@{pkProperty};");

        var connection = _factory.CreateConnection();
        return await connection.ExecuteAsync(updateQuery.ToString(), entity);
    }

    private IEnumerable<string> GetProperties()
    {
        var properties = typeof(T).GetProperties().Where(x => !x.GetAccessors()[0].IsVirtual);
        if (!properties.Any())
            throw new Exception("Entity doesn't have any non-virtual properties");

        return properties.Select(x => x.Name);
    }

    private async Task<int> DeleteRecordAsync(int id, string pkColumnName = "id")
    {
        var connection = _factory.CreateConnection();

        return await connection.ExecuteAsync($"DELETE FROM {_tableName} WHERE {pkColumnName.PascalCaseToSnakeCase()} = @id", new { id });
    }
}