namespace AirportManager.API.Repositories.Interfaces;

public interface IGenericRepository<T> where T : class
{
    Task<IEnumerable<T>> GetAllAsync();
    Task<T?> GetByIdAsync(int id);
    Task<int> CreateAsync(T entity);
    Task<int> CreateAsync(T entity, bool isPkAutoGenerated);
    Task<int> CreateAsync(T entity, bool isPkAutoGenerated, string pkColumnName);
    Task UpdateAsync(T entity);
    Task DeleteAsync(int id);
}