namespace AirportManager.API.Repositories.Interfaces;

public interface IGenericRepository<T> where T : class
{
    Task<IEnumerable<T>> GetAllAsync();
    Task<T?> GetByPkAsync(int id);
    Task<int> CreateAsync(T entity);
    Task<int> CreateAsync(T entity, bool isPkAutoGenerated);
    Task<int> CreateAsync(T entity, bool isPkAutoGenerated, string pkColumnName);
    Task<int> UpdateAsync(T entity);
    Task<int> UpdateAsync(T entity, string pkColumnName);
    Task<int> DeleteAsync(int id);
}